import styles from './legal.module.css';
import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service - IdeaSpot',
  description: 'Terms of Service for IdeaSpot',
};

export default function Terms() {
  return (
    <main className={styles.legalPage}>
      <div className={styles.container}>
        <Link href="/" className={styles.backLink}>← Back to Home</Link>

        <h1 className={styles.title}>Terms of Service</h1>
        <p className={styles.lastUpdated}>Last Updated: November 11, 2025</p>

        <section className={styles.section}>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using IdeaSpot ("the App"), you agree to be bound by these Terms of Service.
            If you do not agree to these terms, please do not use the App.
          </p>
        </section>

        <section className={styles.section}>
          <h2>2. Description of Service</h2>
          <p>
            IdeaSpot is an AI-powered mobile application that helps users validate and develop business ideas
            through conversational AI analysis. The service provides comprehensive analysis cards including
            summaries, actionable insights, user scenarios, monetization strategies, and MVP recommendations.
          </p>
        </section>

        <section className={styles.section}>
          <h2>3. User Accounts</h2>
          <p>
            You may be required to create an account to access certain features. You are responsible for:
          </p>
          <ul>
            <li>Maintaining the confidentiality of your account credentials</li>
            <li>All activities that occur under your account</li>
            <li>Notifying us immediately of any unauthorized use</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the App for any illegal or unauthorized purpose</li>
            <li>Attempt to gain unauthorized access to the App or its systems</li>
            <li>Interfere with or disrupt the App's functionality</li>
            <li>Upload malicious code, viruses, or harmful content</li>
            <li>Violate any applicable laws or regulations</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>5. Intellectual Property</h2>
          <p>
            All content, features, and functionality of IdeaSpot are owned by IdeaSpot and are protected by
            copyright, trademark, and other intellectual property laws. You retain ownership of your idea
            submissions, but grant us a license to process them to provide our services.
          </p>
        </section>

        <section className={styles.section}>
          <h2>6. AI-Generated Content</h2>
          <p>
            The analysis and recommendations provided by IdeaSpot are generated by artificial intelligence
            and should be used as guidance only. We make no guarantees about the accuracy, completeness,
            or suitability of the AI-generated content for any particular purpose.
          </p>
        </section>

        <section className={styles.section}>
          <h2>7. Beta Testing</h2>
          <p>
            During the beta testing period, the App may contain bugs or errors. By participating in the beta,
            you acknowledge that the service is provided "as is" and you assume all risks associated with its use.
          </p>
        </section>

        <section className={styles.section}>
          <h2>8. Limitation of Liability</h2>
          <p>
            IdeaSpot and its affiliates shall not be liable for any indirect, incidental, special, consequential,
            or punitive damages resulting from your use of or inability to use the service.
          </p>
        </section>

        <section className={styles.section}>
          <h2>9. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the App at any time, with or without
            cause, and with or without notice.
          </p>
        </section>

        <section className={styles.section}>
          <h2>10. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the App after changes
            constitutes acceptance of the modified terms.
          </p>
        </section>

        <section className={styles.section}>
          <h2>11. Contact Information</h2>
          <p>
            For questions about these Terms of Service, please contact us at:
            <br />
            Email: support@ideaspot.app
          </p>
        </section>
      </div>
    </main>
  );
}
