import styles from './legal.module.css';
import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service - IdeaSpot',
  description: 'Terms of Service for IdeaSpot',
};

export default function Terms() {
  return (
    <main className={styles.legalPage}>
      <div className={styles.container}>
        <Link href="/" className={styles.backLink}>← Back to Home</Link>

        <h1 className={styles.title}>Terms of Service</h1>
        <p className={styles.lastUpdated}>Last Updated: November 11, 2025</p>

        <section className={styles.section}>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using IdeaSpot ("the App"), you agree to be bound by these Terms of Service.
            If you do not agree to these terms, please do not use the App.
          </p>
        </section>

        <section className={styles.section}>
          <h2>2. Description of Service</h2>
          <p>
            IdeaSpot is an AI-powered mobile application that helps users validate and develop business ideas
            through conversational AI analysis. The service provides comprehensive analysis cards including
            summaries, actionable insights, user scenarios, monetization strategies, and MVP recommendations.
          </p>
        </section>

        <section className={styles.section}>
          <h2>3. User Accounts</h2>
          <p>
            You may be required to create an account to access certain features. You are responsible for:
          </p>
          <ul>
            <li>Maintaining the confidentiality of your account credentials</li>
            <li>All activities that occur under your account</li>
            <li>Notifying us immediately of any unauthorized use</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the App for any illegal or unauthorized purpose</li>
            <li>Attempt to gain unauthorized access to the App or its systems</li>
            <li>Interfere with or disrupt the App's functionality</li>
            <li>Upload malicious code, viruses, or harmful content</li>
            <li>Violate any applicable laws or regulations</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>5. Intellectual Property</h2>
          <p>
            All content, features, and functionality of IdeaSpot are owned by IdeaSpot and are protected by
            copyright, trademark, and other intellectual property laws. You retain ownership of your idea
            submissions, but grant us a license to process them to provide our services.
          </p>
        </section>

        <section className={styles.section}>
          <h2>6. AI-Generated Content</h2>
          <p>
            The analysis and recommendations provided by IdeaSpot are generated by artificial intelligence
            and should be used as guidance only. We make no guarantees about the accuracy, completeness,
            or suitability of the AI-generated content for any particular purpose.
          </p>
        </section>

        <section className={styles.section}>
          <h2>7. Beta Testing</h2>
          <p>
            During the beta testing period, the App may contain bugs or errors. By participating in the beta,
            you acknowledge that the service is provided "as is" and you assume all risks associated with its use.
          </p>
        </section>

        <section className={styles.section}>
          <h2>8. Limitation of Liability</h2>
          <p>
            IdeaSpot and its affiliates shall not be liable for any indirect, incidental, special, consequential,
            or punitive damages resulting from your use of or inability to use the service.
          </p>
        </section>

        <section className={styles.section}>
          <h2>9. Payments and Subscriptions</h2>
          <p>
            IdeaSpot may offer paid subscription plans or in-app purchases. By purchasing a subscription or
            making a payment, you agree to the following:
          </p>
          <ul>
            <li><strong>Pricing:</strong> All prices are subject to change with notice. Current subscribers will be notified of pricing changes.</li>
            <li><strong>Billing:</strong> Subscriptions are billed in advance on a recurring basis (monthly or annually) and will auto-renew unless cancelled.</li>
            <li><strong>Payment Methods:</strong> Payments are processed through Apple's App Store or Google Play Store, subject to their respective terms and policies.</li>
            <li><strong>Cancellation:</strong> You may cancel your subscription at any time through your App Store account settings. Cancellations take effect at the end of the current billing period.</li>
            <li><strong>Refunds:</strong> Refunds are handled according to Apple App Store or Google Play Store policies. Generally, all sales are final unless required by law.</li>
            <li><strong>Free Trials:</strong> Free trial periods, if offered, will automatically convert to paid subscriptions unless cancelled before the trial ends.</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>10. Warranties and Disclaimers</h2>
          <p>
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
            TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:
          </p>
          <ul>
            <li>WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT</li>
            <li>WARRANTIES REGARDING THE ACCURACY, RELIABILITY, OR COMPLETENESS OF AI-GENERATED CONTENT</li>
            <li>WARRANTIES THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE</li>
            <li>WARRANTIES REGARDING THE RESULTS OBTAINED FROM USING THE SERVICE</li>
          </ul>
          <p>
            <strong>IMPORTANT:</strong> Business decisions based on AI-generated analysis are made at your sole risk.
            We do not guarantee business success, profitability, or any specific outcomes from implementing
            recommendations provided by the App.
          </p>
          <p>
            You acknowledge that the App is in beta and may contain bugs, errors, or other issues that could cause
            system failures, data loss, or other problems. You assume all risks associated with your use of the App.
          </p>
        </section>

        <section className={styles.section}>
          <h2>11. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless IdeaSpot, its affiliates, officers, directors, employees,
            and agents from any claims, liabilities, damages, losses, costs, or expenses (including reasonable attorneys'
            fees) arising from:
          </p>
          <ul>
            <li>Your use of the App or services</li>
            <li>Your violation of these Terms of Service</li>
            <li>Your violation of any rights of another party</li>
            <li>Any content or ideas you submit through the App</li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2>12. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the App at any time, with or without
            cause, and with or without notice. Upon termination:
          </p>
          <ul>
            <li>Your right to use the App immediately ceases</li>
            <li>Any outstanding fees owed to us become immediately due and payable</li>
            <li>We may delete your account data in accordance with our Privacy Policy</li>
          </ul>
          <p>
            Sections of these Terms that by their nature should survive termination will survive, including but not
            limited to warranty disclaimers, limitations of liability, and dispute resolution provisions.
          </p>
        </section>

        <section className={styles.section}>
          <h2>13. Dispute Resolution and Governing Law</h2>
          <h3>13.1 Governing Law</h3>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the State of California,
            United States, without regard to its conflict of law provisions.
          </p>

          <h3>13.2 Arbitration Agreement</h3>
          <p>
            Any dispute, controversy, or claim arising out of or relating to these Terms or the breach, termination,
            enforcement, interpretation, or validity thereof, including the determination of the scope or applicability
            of this agreement to arbitrate, shall be determined by binding arbitration in California, before a single
            arbitrator. The arbitration shall be administered by JAMS pursuant to its Comprehensive Arbitration Rules
            and Procedures.
          </p>
          <p>
            <strong>CLASS ACTION WAIVER:</strong> You agree that any arbitration or proceeding shall be limited to
            the dispute between us and you individually. To the full extent permitted by law, (1) no arbitration or
            proceeding shall be joined with any other; (2) there is no right or authority for any dispute to be
            arbitrated on a class-action basis or to utilize class action procedures; and (3) there is no right or
            authority for any dispute to be brought in a purported representative capacity on behalf of the general
            public or any other persons.
          </p>

          <h3>13.3 Exceptions to Arbitration</h3>
          <p>
            Either party may seek enforcement of this arbitration agreement or any arbitration award in any court of
            competent jurisdiction. Additionally, you and we both retain the right to bring an individual action in
            small claims court and the right to seek injunctive or other equitable relief in a court of competent
            jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of a party's
            copyrights, trademarks, trade secrets, patents, or other intellectual property rights.
          </p>

          <h3>13.4 30-Day Right to Opt Out</h3>
          <p>
            You have the right to opt out of this arbitration agreement by sending written notice of your decision
            to opt out to support@ideaspot.app within 30 days of first accepting these Terms. Your notice must include
            your name and address. If you opt out, all other parts of these Terms will continue to apply.
          </p>
        </section>

        <section className={styles.section}>
          <h2>14. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the App after changes
            constitutes acceptance of the modified terms.
          </p>
        </section>

        <section className={styles.section}>
          <h2>15. Contact Information</h2>
          <p>
            For questions about these Terms of Service, please contact us at:
            <br />
            Email: support@ideaspot.app
          </p>
        </section>
      </div>
    </main>
  );
}
